version: '3.8'

services:
  db:
    image: postgres:16
    container_name: web_database_xvup
    environment:
      POSTGRES_DB: web_database_xvup
      POSTGRES_USER: web_database_xvup_user
      POSTGRES_PASSWORD: your_password_here  # ← замени на свой пароль
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
